# schemas/__init__.py
from .user import UserBase, UserCreate, User, UserResponse

from .token import Token, TokenData, TokenCreate
from .product import (
    ProductBase,
    ProductCreate,
    ProductUpdate,
    Product,
    ProductResponse,
)
from .cart import (
    CartItemBase,
    CartItemCreate,
    CartItemUpdate,
    CartItem,
    CartAddResponse,
    CartUpdateResponse,
    CartRemoveResponse,
    CartClearResponse,
    CartTotalResponse,
    CartDiscountRequest,
    CartDiscountResponse,
    CartSaveRequest,
    CartSaveResponse,
    ProductInCart,
)
from .order import (
    OrderItemBase,
    OrderItemCreate,
    OrderItem,
    OrderBase,
    OrderCreate,
    OrderUpdate,
    Order,
    OrderCreateResponse,
    OrderUpdateResponse,
    OrderStatusHistory,
)
from .reward import (
    RewardBase,
    RewardCreate,
    RewardUpdate,
    RewardRedeemRequest,
    Reward,
    RewardCreateResponse,
    RewardUpdateResponse,
    RewardCancelResponse,
    RewardRedeemResponse,
)

__all__ = [
    "UserBase",
    "UserCreate",
    "User",
    "UserResponse",
    "ProductBase",
    "ProductCreate",
    "ProductUpdate",
    "Product",
    "ProductResponse",
    "CartItemBase",
    "CartItemCreate",
    "CartItemUpdate",
    "CartItem",
    "CartAddResponse",
    "CartUpdateResponse",
    "CartRemoveResponse",
    "CartClearResponse",
    "CartTotalResponse",
    "CartDiscountRequest",
    "CartDiscountResponse",
    "CartSaveRequest",
    "CartSaveResponse",
    "ProductInCart",
    "OrderItemBase",
    "OrderItemCreate",
    "OrderItem",
    "OrderBase",
    "OrderCreate",
    "OrderUpdate",
    "Order",
    "OrderCreateResponse",
    "OrderUpdateResponse",
    "OrderStatusHistory",
    "RewardBase",
    "RewardCreate",
    "RewardUpdate",
    "RewardRedeemRequest",
    "Reward",
    "RewardCreateResponse",
    "RewardUpdateResponse",
    "RewardCancelResponse",
    "RewardRedeemResponse",
    "Token",
    "TokenData",
    "TokenCreate",
]
