version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: npm run dev
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
